package stacks

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/raylsnetwork/rayls-sovereign-cli/internal/docker"
	"github.com/raylsnetwork/rayls-sovereign-cli/internal/envfile"

	"github.com/fatih/color"
	"gopkg.in/yaml.v3"
)

// devOverrideFile is written and owned by `rayls dev`. Compose auto-merges it
// over docker-compose.yaml, swapping dev-mode components to their local
// checkout (air-based dev images with hot reload where supported).
const devOverrideFile = "docker-compose.override.yaml"

// devOverrideMarker is the first line of every override we generate; we refuse
// to overwrite a file that doesn't carry it (it's the user's, not ours).
const devOverrideMarker = "# Generated by `rayls dev` — DO NOT EDIT; managed by the Rayls CLI."

// composeCmd builds a docker compose invocation honoring the detected
// compose version, with streams attached to the terminal.
func composeCmd(args ...string) (*exec.Cmd, error) {
	version, err := docker.CheckDockerConfig()
	if err != nil {
		return nil, err
	}
	var cmd *exec.Cmd
	if version == docker.ComposeV2 {
		cmd = exec.Command("docker", append([]string{"compose"}, args...)...)
	} else {
		cmd = exec.Command("docker-compose", args...)
	}
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd, nil
}

// composeServiceNames returns the service names defined in the stack's
// docker-compose.yaml.
func composeServiceNames() ([]string, error) {
	data, err := os.ReadFile("docker-compose.yaml")
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no docker-compose.yaml in the current directory — run `rayls init --local` first")
		}
		return nil, err
	}
	var compose struct {
		Services map[string]interface{} `yaml:"services"`
	}
	if err := yaml.Unmarshal(data, &compose); err != nil {
		return nil, fmt.Errorf("parsing docker-compose.yaml: %w", err)
	}
	names := make([]string, 0, len(compose.Services))
	for name := range compose.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

// devService pairs a compose service with the build config of the component
// service prefix it was generated from.
type devService struct {
	name   string
	prefix string
	build  docker.ServiceBuild
}

// servicesForComponent maps a component to the compose services built from
// it. A prefix matches the bare service name ("contracts") or participant-
// suffixed ones ("kos-a").
func servicesForComponent(c *docker.Component, allServices []string) []devService {
	var out []devService
	for prefix, sb := range c.Services {
		for _, name := range allServices {
			if name == prefix || strings.HasPrefix(name, prefix+"-") {
				out = append(out, devService{name: name, prefix: prefix, build: sb})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// participantIndex derives the participant offset from a service name suffix
// ("kos-a" -> 0, "kos-b" -> 1). Services without a participant suffix
// ("contracts") return 0.
func participantIndex(serviceName string) int {
	if i := strings.LastIndex(serviceName, "-"); i >= 0 && i == len(serviceName)-2 {
		c := serviceName[len(serviceName)-1]
		if c >= 'a' && c <= 'f' {
			return int(c - 'a')
		}
	}
	return 0
}

// envFileFor returns the per-participant env file the dev (air) images read
// via the ENV_FILE variable, matching what the base compose passes to the
// production entrypoints via `--env`.
func envFileFor(c *docker.Component, serviceName string) string {
	suffix := "A"
	if i := strings.LastIndex(serviceName, "-"); i >= 0 && i == len(serviceName)-2 {
		suffix = strings.ToUpper(serviceName[i+1:])
	}
	return fmt.Sprintf("/parfin/%s/.%s.env", c.DirName, suffix)
}

// debugPortFor mirrors the GO_DEBUG_PORT layout of the base compose (dlv
// inside the air images listens here; the base compose already maps it).
func debugPortFor(prefix string, serviceName string) int {
	base := map[string]int{"kos": 4000, "pubrelayer": 4050}[prefix]
	return base + participantIndex(serviceName)
}

// srcRoot is where `rayls dev` places (and looks for) component checkouts:
// RAYLS_SRC_DIR if set, else the parent of the stack directory, so checkouts
// sit side by side with the stack.
func srcRoot(fileVars map[string]string) string {
	if dir := envfile.Lookup(fileVars, "RAYLS_SRC_DIR"); dir != "" {
		return dir
	}
	return ".."
}

// ensureCheckout clones repo into dir at ref when dir doesn't exist yet.
// An existing directory is used as-is — whatever the developer has checked
// out is what builds; that's the point of dev mode.
func ensureCheckout(dir, repo, ref string) error {
	if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
		fmt.Printf("✓ Using existing checkout %s\n", dir)
		return nil
	}
	fmt.Printf("Cloning %s (at %s) into %s...\n", repo, ref, dir)
	clone := exec.Command("git", "clone", repo, dir)
	clone.Stdout = os.Stdout
	clone.Stderr = os.Stderr
	if err := clone.Run(); err != nil {
		return fmt.Errorf("cloning %s: %w", repo, err)
	}
	checkout := exec.Command("git", "-C", dir, "checkout", "-q", ref)
	checkout.Stderr = os.Stderr
	if err := checkout.Run(); err != nil {
		return fmt.Errorf("checking out %s in %s: %w", ref, dir, err)
	}
	return nil
}

// EnableDev switches the given components to dev mode: ensures a local
// checkout exists (cloning at the pinned ref when missing), records the
// checkout path as <PREFIX>_SRC in .env, regenerates the compose override
// with build + hot-reload wiring, and rebuilds the affected services.
// repoOverride/srcOverride apply only when a single component is given.
func EnableDev(keys []string, repoOverride, srcOverride string) error {
	if len(keys) > 1 && (repoOverride != "" || srcOverride != "") {
		return fmt.Errorf("--repo/--src only apply to a single component")
	}
	if _, err := composeServiceNames(); err != nil {
		return err
	}

	fileVars, err := envfile.Load(".env")
	if err != nil {
		return err
	}
	srcs, err := docker.ResolveSources()
	if err != nil {
		return err
	}

	for _, key := range keys {
		comp := docker.ComponentByKey(key)
		if comp == nil {
			return fmt.Errorf("unknown component %q (valid: %s)", key, strings.Join(componentKeys(), ", "))
		}
		src := srcs.Src(*comp)
		if srcOverride != "" {
			src = srcOverride
		}
		if src == "" {
			src = filepath.Join(srcRoot(fileVars), comp.DirName)
		}
		repo := srcs.Repo(*comp)
		if repoOverride != "" {
			repo = repoOverride
		}
		if err := ensureCheckout(src, repo, srcs.Ref(*comp)); err != nil {
			return err
		}
		// Recorded verbatim — for the default sibling layout that's a RELATIVE
		// path (../<repo>), same as the pins pinLocalSources records: compose
		// resolves build contexts against the compose file's directory and
		// every rayls command runs from the stack directory, so relative pins
		// keep the .env portable. An explicit --src / RAYLS_SRC_DIR is honored
		// as given, absolute or not.
		if err := envfile.Set(".env", comp.EnvPrefix+"_SRC", src); err != nil {
			return err
		}
		fmt.Printf("✓ %s: dev mode ON (%s_SRC=%s)\n", comp.Key, comp.EnvPrefix, src)
	}

	if err := RegenerateDevOverride(); err != nil {
		return err
	}
	return rebuildComponents(keys)
}

// DisableDev switches components back to their pinned from-source builds:
// removes <PREFIX>_SRC from .env, regenerates (or removes) the override, and
// rebuilds the affected services from the pinned git context.
func DisableDev(keys []string) error {
	for _, key := range keys {
		comp := docker.ComponentByKey(key)
		if comp == nil {
			return fmt.Errorf("unknown component %q (valid: %s)", key, strings.Join(componentKeys(), ", "))
		}
		if err := envfile.Unset(".env", comp.EnvPrefix+"_SRC"); err != nil {
			return err
		}
		fmt.Printf("✓ %s: dev mode OFF (building from pinned source)\n", comp.Key)
	}
	if err := RegenerateDevOverride(); err != nil {
		return err
	}
	return rebuildComponents(keys)
}

// DevStatus prints each component's current source: local checkout (dev mode)
// or the pinned git context it builds from.
func DevStatus() error {
	srcs, err := docker.ResolveSources()
	if err != nil {
		return err
	}
	green := color.New(color.FgGreen).SprintFunc()
	for _, comp := range docker.Components {
		if src := srcs.Src(comp); src != "" {
			fmt.Printf("%-10s %s %s\n", comp.Key, green("dev"), src)
		} else {
			fmt.Printf("%-10s pinned %s#%s\n", comp.Key, srcs.Repo(comp), srcs.Ref(comp))
		}
	}
	return nil
}

func componentKeys() []string {
	keys := make([]string, len(docker.Components))
	for i, c := range docker.Components {
		keys[i] = c.Key
	}
	return keys
}

// rebuildComponents rebuilds and recreates just the services belonging to the
// given components, leaving the rest of the stack (and its state) untouched.
func rebuildComponents(keys []string) error {
	allServices, err := composeServiceNames()
	if err != nil {
		return err
	}
	var services []string
	for _, key := range keys {
		comp := docker.ComponentByKey(key)
		for _, ds := range servicesForComponent(comp, allServices) {
			services = append(services, ds.name)
		}
	}
	if len(services) == 0 {
		return nil
	}
	// Up-path: same key guard as StartServices.
	if publicChainKeyGuardApplies(services) {
		if err := CheckPublicChainKey(); err != nil {
			return err
		}
	}
	fmt.Printf("\nRebuilding: %s\n", strings.Join(services, ", "))
	cmd, err := composeCmd(append([]string{"up", "-d", "--build", "--no-deps"}, services...)...)
	if err != nil {
		return err
	}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("rebuilding services: %w", err)
	}
	// A rebuilt contracts image doesn't redeploy: the deploy is one-shot per
	// stack (its OpenZeppelin manifests live in the shared-config volume, which
	// also masks the rebuilt /parfin tree), so the restarted container reports
	// the existing deployment and skips.
	for _, key := range keys {
		if key == "contracts" {
			fmt.Printf("\n%s\n", color.New(color.FgYellow).Sprint("Note: contract changes need a fresh stack — the deploy is one-shot per stack.\nRun `rayls down -v` then `rayls init ...` to deploy the rebuilt contracts."))
			break
		}
	}
	return nil
}

// Watch runs `docker compose watch` in the foreground, syncing file saves in
// dev-mode checkouts into their containers. Compose v1 has no watch.
func Watch() error {
	version, err := docker.CheckDockerConfig()
	if err != nil {
		return err
	}
	if version != docker.ComposeV2 {
		return fmt.Errorf("`docker compose watch` needs Compose v2 (>= 2.22); docker-compose v1 detected")
	}
	if _, err := os.Stat(devOverrideFile); os.IsNotExist(err) {
		return fmt.Errorf("no component is in dev mode — run `rayls dev <component>` first")
	}
	// `compose watch` implicitly ups services; same key guard.
	if err := CheckPublicChainKey(); err != nil {
		return err
	}
	cmd, err := composeCmd("watch")
	if err != nil {
		return err
	}
	return cmd.Run()
}

// RegenerateDevOverride rewrites docker-compose.override.yaml from the set of
// components currently in dev mode (<PREFIX>_SRC present in .env / the
// environment). With no components in dev mode the file is removed. The
// override swaps each dev component's build to its local checkout and its
// air-based dev Dockerfile (`build: !override` so the base git context — and
// its ssh requirement — is fully replaced), overrides the command to run air
// (the production images run compiled binaries via ENTRYPOINT; the dev images
// rebuild from /app source on every change), sets the ENV_FILE/GO_DEBUG_PORT
// vars air consumes, and adds a compose-watch sync rule into /app plus a Go
// build-cache volume so in-container rebuilds are fast. Components without a
// dev Dockerfile (contracts) only get the local-checkout build swap.
// Requires Docker Compose >= 2.24 (the !override tag).
func RegenerateDevOverride() error {
	srcs, err := docker.ResolveSources()
	if err != nil {
		return err
	}
	allServices, err := composeServiceNames()
	if err != nil {
		return err
	}

	// Refuse to clobber a hand-written override.
	if data, err := os.ReadFile(devOverrideFile); err == nil {
		if !strings.HasPrefix(string(data), devOverrideMarker) {
			return fmt.Errorf("%s exists but was not generated by `rayls dev` — move it aside first", devOverrideFile)
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	var b strings.Builder
	var volumes []string
	for _, comp := range docker.Components {
		src := srcs.Src(comp)
		if src == "" {
			continue
		}
		for _, ds := range servicesForComponent(&comp, allServices) {
			fmt.Fprintf(&b, "    %s:\n", ds.name)
			dockerfile := ds.build.Dockerfile
			if comp.Watch && ds.build.DevDockerfile != "" {
				dockerfile = ds.build.DevDockerfile
			}
			fmt.Fprintf(&b, "        build: !override\n")
			fmt.Fprintf(&b, "            context: %q\n", src)
			if dockerfile != "" {
				fmt.Fprintf(&b, "            dockerfile: %q\n", dockerfile)
			}
			fmt.Fprintf(&b, "        pull_policy: build\n")
			if comp.Watch && ds.build.DevDockerfile != "" {
				gocache := "gocache-" + ds.name
				volumes = append(volumes, gocache)
				// air consumes ENV_FILE/GO_DEBUG_PORT env vars (the production
				// entrypoints take `--env` as a command argument instead).
				fmt.Fprintf(&b, "        command: air -c %s\n", ds.build.AirConfig)
				fmt.Fprintf(&b, "        environment:\n")
				fmt.Fprintf(&b, "            - ENV_FILE=%s\n", envFileFor(&comp, ds.name))
				fmt.Fprintf(&b, "            - GO_DEBUG_PORT=%d\n", debugPortFor(ds.prefix, ds.name))
				fmt.Fprintf(&b, "        develop:\n")
				fmt.Fprintf(&b, "            watch:\n")
				fmt.Fprintf(&b, "                - action: sync\n")
				fmt.Fprintf(&b, "                  path: %q\n", src)
				fmt.Fprintf(&b, "                  target: /app\n")
				fmt.Fprintf(&b, "                  ignore:\n")
				fmt.Fprintf(&b, "                      - .git\n")
				fmt.Fprintf(&b, "        volumes:\n")
				fmt.Fprintf(&b, "            - %s:/root/.cache/go-build\n", gocache)
			}
		}
	}

	if b.Len() == 0 {
		if err := os.Remove(devOverrideFile); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}

	var out strings.Builder
	out.WriteString(devOverrideMarker + "\n")
	out.WriteString("# Components in dev mode build from their local checkout (<COMPONENT>_SRC in\n")
	out.WriteString("# .env) instead of the pinned git context. Run `rayls watch` for hot reload;\n")
	out.WriteString("# `rayls dev --off <component>` reverts to the pinned build.\n")
	out.WriteString("services:\n")
	out.WriteString(b.String())
	if len(volumes) > 0 {
		out.WriteString("volumes:\n")
		for _, v := range volumes {
			fmt.Fprintf(&out, "    %s: {}\n", v)
		}
	}
	return os.WriteFile(devOverrideFile, []byte(out.String()), 0644)
}
